# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhub', '0002_auto_20160413_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lagosians',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='lasgidi',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='wizzy',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
