# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhub', '0003_auto_20160414_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wizzy',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
