# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhub', '0004_auto_20160414_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wizzy',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
