# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhub', '0005_auto_20160415_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wizzy',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
