# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhub', '0006_auto_20160415_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wizzy',
            name='last_name',
            field=models.CharField(max_length=200),
        ),
    ]
