# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhub', '0008_auto_20160415_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wizzy',
            name='password',
            field=models.DateField(max_length=200),
        ),
    ]
