# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_music'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subject', models.TextField(max_length=500)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
