# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20160519_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.CharField(default='jaywizzy', max_length=250),
            preserve_default=False,
        ),
    ]
