# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_contact_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='date_released',
            field=models.DateField(max_length=50),
        ),
    ]
