# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20160526_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('article_no', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
