# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_articles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelTable(
            name='articles',
            table='Articles',
        ),
    ]
