# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20160601_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='article',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
