# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_articles_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
