# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-15 10:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mouth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 15, 10, 8, 24, 826087, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
