# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-08 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mouth', '0003_auto_20160705_1559'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userlogin',
            table='userlogin',
        ),
    ]
