# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-25 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mouth', '0004_auto_20160708_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
